# docker-compose.yml
version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    restart: always
    volumes:
      - ./:/pony-coffee
      - /pony-coffee/node_modules
      - /pony-coffee/.next
    ports:
      - 3000:3000